name: Playwright Tests
on:
  push:
    branches: [ visualTesting, master ]
  pull_request:
    branches: [ visualTesting, master ]
jobs:
  test:
    env:
    export APPLITOOL_API_KEY=$APPLITOOL_API_KEY
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Run environment variables
      run: env
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
